// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRUDJ7Tmh30NJ0lNn9-LKPpVW5UuHjEMw',
    appId: '1:237426452124:web:e7765443435e9a97cf2f59',
    messagingSenderId: '237426452124',
    projectId: 'bayad-66764',
    authDomain: 'bayad-66764.firebaseapp.com',
    storageBucket: 'bayad-66764.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAJ8HvGjke5MzZPvkOvppBLBlBQuSgYLU',
    appId: '1:237426452124:android:798c144c36f175a7cf2f59',
    messagingSenderId: '237426452124',
    projectId: 'bayad-66764',
    storageBucket: 'bayad-66764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDRiuQ7l0UXvFYxe3yQgieEMXMC5B0SVQ',
    appId: '1:237426452124:ios:94e9e089a7a19e6ecf2f59',
    messagingSenderId: '237426452124',
    projectId: 'bayad-66764',
    storageBucket: 'bayad-66764.appspot.com',
    iosBundleId: 'com.example.bayad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDRiuQ7l0UXvFYxe3yQgieEMXMC5B0SVQ',
    appId: '1:237426452124:ios:c6d3e8261dee8818cf2f59',
    messagingSenderId: '237426452124',
    projectId: 'bayad-66764',
    storageBucket: 'bayad-66764.appspot.com',
    iosBundleId: 'com.example.bayad.RunnerTests',
  );
}
